### ISSUE TITLE
Описать правила сообщений к коммитам

### ISSUE THREAD

**Issue by nzinoviev** [nzinoviev/BabbleChat#2]
Необходимо стандартизировать процесс написания сообщений к коммитам, чтобы обеспечить понятность и однозначность истории изменений в проекте. Это важно для поддержания высокого качества кода, упрощения ревью, а также для облегчённого поиска и отслеживания изменений.

## Технические детали
Документ должен содержать следующие разделы:
* Формат заголовка коммита
* Формат тела коммита
* Примеры правильных и неправильных сообщений

## Результат
Статья на wiki с правила написания сообщений к коммитам.

**Comment by juzinovieva** [comment]
[Правила оформления описания к коммитам](https://github.com/nzinoviev/BabbleChat/wiki/%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B9-%D0%BA-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82%D0%B0%D0%BC)
